project:
  type: book

book:
  title: "quarto_test"
  author: "Norah Jones"
  date: "31/7/2024"
  chapters:
    - index.qmd

bibliography: references.bib

execute: 
  cache: false
  freeze: false

format:
  pdf:
    documentclass: scrreprt



